stages:
    - lint
    - test

lint:
    stage: lint
    image: rust:latest
    script:
        - cargo clippy --verbose

test:
    stage: build
    image: rustlang/rust:nightly
    script:
        - cargo test --verbose
