stages:
    - lint
    - test

nightly-lint:
    stage: lint
    image: rustlang/rust:nightly
    script:
        - cargo clippy --verbose

nightly-test:
    stage: test
    image: rustlang/rust:nightly
    script:
        - cargo test --verbose
