[package]
name = "rena"
version = "0.1.0"
authors = ["Lyssieth <raxixor@rax.ee>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paris = { version = "1.5", features = ["macros", "timestamps", "no_logger"] }
regex = "1.3"
clap = "3.0.0-beta.2"
color-eyre = "0.5"
