[package]
authors = ["Lyssieth <raxixor@rax.ee>"]
description = "A bulk file renaming utility."
documentation = "https://github.com/lyssieth/rena/wiki"
edition = "2018"
keywords = ["utility", "tool", "cli"]
license = "MIT"
name = "rena"
readme = "README.md"
repository = "https://github.com/lyssieth/rena"
version = "1.2.0"

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["suggestions", "color", "wrap_help"] }
color-eyre = { version = "0.5", features = ["issue-url"] }
paris = { version = "1.5", features = ["macros", "no_logger"] }
regex = "1.4"
strfmt = "0.1"
